# Generated by Django 4.0.3 on 2022-03-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_imagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='price',
            field=models.FloatField(),
        ),
    ]
