# Generated by Django 4.0.3 on 2022-04-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_foodmenu_digital_alter_foodmenu_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
