# Generated by Django 4.0.3 on 2022-04-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_foodmenu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmenu',
            name='digital',
        ),
    ]
