# Generated by Django 4.0.3 on 2022-04-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_car_cart_rename_carproduct_cartproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='full_name',
        ),
    ]
